begin;
do $$
declare adm uuid:=gen_random_uuid(); a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); other uuid:=gen_random_uuid(); ev uuid; tid uuid; j jsonb; sl text:='qa-roster-'||gen_random_uuid();
begin
 insert into auth.users(id,email,raw_user_meta_data) values(adm,adm||'@example.invalid','{}'),(a,a||'@example.invalid','{}'),(b,b||'@example.invalid','{}'),(other,other||'@example.invalid','{}');
 insert into public.tg_admins(user_id) values(adm);
 insert into public.tg_events(slug,title,event_date,max_teams) values(sl,'QA ONLY',now()+interval '30 days',24) returning id into ev;
 perform set_config('request.jwt.claim.sub',a::text,true);
 begin perform public.arc_admin_add_partner(gen_random_uuid(),b);raise exception 'FAIL_AUTH';exception when others then if sqlerrm<>'ADMIN_ONLY' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',adm::text,true);
 execute 'set local role authenticated';
 perform public.arc_admin_action('save_profile',jsonb_build_object('user_id',a,'nickname','QA Captain','full_name','QA Captain','gender','male','phone','01000000001'));
 perform public.arc_admin_action('save_profile',jsonb_build_object('user_id',b,'nickname','QA Partner','full_name','QA Partner','gender','female','phone','01000000002'));
 execute 'reset role';
 insert into public.tg_teams(event_id,team_name,player_1,player_2,phone,photo_url,status,division,category,payment_status,pricing_tier,amount_due) values(ev,'QA Team','QA Captain','TEAMMATE PENDING','01000000001','https://arcstation.kr/favicon.png','confirmed','OPEN','MIXED','paid','admin',0) returning id into tid;
 insert into public.tg_team_members(team_id,event_id,athlete_id,member_role) values(tid,ev,a,'captain');
 insert into private.arc_entry_invites(team_id,invitee_id) values(tid,b);
 execute 'set local role authenticated';
 begin perform public.arc_admin_add_partner(tid,other);raise exception 'FAIL_PROFILE';exception when others then if sqlerrm<>'PARTNER_PROFILE_REQUIRED' then raise;end if;end;
 begin perform public.arc_admin_add_partner(tid,a);raise exception 'FAIL_SELF';exception when others then if sqlerrm<>'CANNOT_ADD_CAPTAIN' then raise;end if;end;
 j:=public.arc_admin_rosters(sl);if (j->0->>'member_count')::int<>1 then raise exception 'FAIL_COUNT';end if;
 execute 'reset role';
 update public.tg_teams set payment_status='unpaid' where id=tid;
 execute 'set local role authenticated';
 begin perform public.arc_admin_add_partner(tid,b);raise exception 'FAIL_PAYMENT';exception when others then if sqlerrm<>'PAYMENT_NOT_CONFIRMED' then raise;end if;end;
 execute 'reset role';
 update public.tg_teams set payment_status='paid',category='MM' where id=tid;
 execute 'set local role authenticated';
 begin perform public.arc_admin_add_partner(tid,b);raise exception 'FAIL_CATEGORY';exception when others then if sqlerrm<>'CATEGORY_GENDER_MISMATCH' then raise;end if;end;
 execute 'reset role';update public.tg_teams set category='MIXED' where id=tid;execute 'set local role authenticated';
 perform public.arc_admin_add_partner(tid,b);
 j:=public.arc_admin_add_partner(tid,b);if not (j->>'already_added')::boolean then raise exception 'FAIL_IDEMPOTENCY';end if;
 j:=public.arc_admin_rosters(sl);if j->0->>'partner_id'<>b::text then raise exception 'FAIL_PARTNER';end if;
 execute 'reset role';
 if (select count(*) from public.tg_team_members where team_id=tid and active)<>2 then raise exception 'FAIL_MEMBERS';end if;
 if not exists(select 1 from private.arc_entry_invites where team_id=tid and status='accepted' and confirmation_method='admin') then raise exception 'FAIL_INVITE';end if;
 if (select player_2 from public.tg_teams where id=tid)<>'QA Partner' then raise exception 'FAIL_NAME';end if;
 if not exists(select 1 from private.arc_admin_audit where action='admin_add_partner' and target_id=b) then raise exception 'FAIL_AUDIT';end if;
 if has_function_privilege('anon','public.arc_admin_add_partner(uuid,uuid)','execute') then raise exception 'FAIL_ANON';end if;
end $$;
rollback;
select 'PASS: admin role, profile validation, captain exclusion, roster read, immediate join, retry idempotency, invite acceptance, audit, anon denied' as result;
