const C=window.TG_CONFIG;
const db=window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey);
function nav(active){const p=[["HOME","index.html"],["EVENT","event.html"],["TEAMS","teams.html"],["FAN PICK","fanpick.html"],["LIVE","live.html"],["ARCHIVE","archive.html"]];return `<header class="nav"><div class="container navin"><a class="brand" href="index.html">TEAM GAMES</a><nav class="links">${p.map(([n,h])=>`<a class="${active===n?'active':''}" href="${h}">${n}</a>`).join('')}</nav><a class="cta" href="teams.html#register">REGISTER</a></div></header>`}
function shell(active){document.querySelector('#nav').innerHTML=nav(active);document.querySelector('#footer').innerHTML=`<footer class="footer"><div class="container">TEAM GAMES · Edition #01 · OCT 31, 2026 · Seoul</div></footer>`}
function notice(id,msg,err=false){const e=document.getElementById(id);if(!e)return;e.textContent=msg;e.style.display='block';e.classList.toggle('err',err)}
function token(){let t=localStorage.getItem('tg_device_token');if(!t){t=crypto.randomUUID();localStorage.setItem('tg_device_token',t)}return t}
async function event(){const {data,error}=await db.from('tg_events').select('*').eq('slug',C.eventSlug).single();if(error)throw error;return data}
async function teams(){const e=await event();const {data,error}=await db.from('tg_teams').select('id,event_id,team_name,player_1,player_2,photo_url,heat_no,station_no,status,created_at').eq('event_id',e.id).eq('status','confirmed').order('created_at');if(error)throw error;return data||[]}
function countdown(){const el=document.getElementById('countdown');if(!el)return;const target=new Date(C.eventDateISO);const tick=()=>{let d=Math.max(0,target-new Date()),days=Math.floor(d/864e5);d%=864e5;let h=Math.floor(d/36e5);d%=36e5;let m=Math.floor(d/6e4),s=Math.floor((d%6e4)/1e3);el.innerHTML=[["DAYS",days],["HOURS",h],["MIN",m],["SEC",s]].map(([l,v])=>`<div class="card"><b>${String(v).padStart(2,'0')}</b><span>${l}</span></div>`).join('')};tick();setInterval(tick,1000)}
