const fp=id=>document.getElementById(id),points=v=>Number(v||0).toLocaleString('ko-KR')+' P';
const pickCategory=v=>({MM:'MEN’S · 남남',WW:'WOMEN’S · 여여',MIXED:'MIXED · 남녀'}[v]||v);
const pickStatus=v=>({pending:'결과 대기',won:'적중',lost:'미적중',refunded:'포인트 반환'}[v]||'결과 대기');
let fanUser=null,fanAccount=null,pickRows=[],selectedPick=null,pickBusy=false,refreshBusy=false;
async function pickRpc(name,args){const q=await db.rpc(name,args);if(q.error)throw q.error;return q.data;}
function pickError(e){const m=String(e?.message||e);return Object.entries({AUTH_REQUIRED:'로그인 후 다시 시도해 주세요.',INVALID_STAKE:'100 P 이상, 100 P 단위로 입력해 주세요.',MARKET_LOCKED:'이 경기의 예측 접수가 마감되었습니다.',BET_ALREADY_PLACED:'이미 접수한 경기입니다. 내 예측 내역을 확인하세요.',INSUFFICIENT_POINTS:'보유 포인트가 부족합니다.',TEAM_NOT_IN_MARKET:'현재 선택할 수 없는 팀입니다. 보드를 새로고침해 주세요.',FAN_PROFILE_REQUIRED:'계정 정보를 새로고침한 뒤 다시 시도해 주세요.'}).find(([k])=>m.includes(k))?.[1]||'처리 결과를 확인하지 못했습니다. 다시 접수하기 전에 새로고침하여 내역을 확인해 주세요.';}
function renderWallet(){
 if(!fanUser){fp('fanWallet').innerHTML='<p class="arc-kicker">PLAYER NOT CONNECTED</p><h2>관중도 플레이어입니다.</h2><p>계정으로 로그인하면 내 포인트와 적중률을 확인할 수 있어요.</p><a class="arc-button neon-pink" href="account.html?next=fanpick.html">로그인 / 회원가입 →</a>';return;}
 const a=fanAccount;if(!a){fp('fanWallet').innerHTML='<p>포인트를 불러오지 못했습니다. 새로고침해 주세요.</p>';return;}
 fp('fanWallet').innerHTML='<div class="wallet-top"><div><p class="arc-kicker">'+esc(a.display_name)+' / PLAY POINT</p><strong class="wallet-balance">'+points(a.balance)+'</strong><span class="fan-note">현재 사용 가능한 포인트</span></div><a class="arc-button" href="my.html">내 계정 ↗</a></div><div class="fan-stats"><div><span>적중률</span><b>'+(a.settled_bets?Number(a.hit_rate).toFixed(1)+'%':'—')+'</b></div><div><span>적중 / 정산</span><b>'+Number(a.wins||0)+' / '+Number(a.settled_bets||0)+'</b></div><div><span>정산 순증감</span><b>'+(a.net_win>0?'+':'')+points(a.net_win)+'</b></div><div><span>누적 사용 포인트</span><b>'+points(a.total_staked)+'</b></div></div><p class="fan-note">통계는 전체 예측 기준 · 적중률과 순증감은 정산이 끝난 예측만 반영됩니다.</p>';
}
function renderBoard(){
 if(!pickRows.length){fp('pickBoard').innerHTML='<section class="neon-panel empty-cabinet"><span class="pixel-icon" aria-hidden="true">◈</span><p class="arc-kicker">NEXT GAME LOADING</p><h2>예측 보드 오픈 대기</h2><p>운영자가 예측을 열면 여기서 바로 팀을 선택할 수 있어요.<br>지금은 참가팀과 경기 방식을 살펴보세요.</p><div class="arc-actions"><a class="arc-button" href="teams.html">참가팀 보기 →</a><a class="arc-button" href="event.html">경기 안내 →</a></div></section>';return;}
 const groups=Map.groupBy?Map.groupBy(pickRows,r=>r.market_id):pickRows.reduce((m,r)=>(m.has(r.market_id)?m.get(r.market_id).push(r):m.set(r.market_id,[r]),m),new Map());
 fp('pickBoard').innerHTML=[...groups.values()].map(rows=>{const m=rows[0],open=m.market_status==='open'&&new Date(m.lock_at)>new Date(),hasBet=!!m.user_bet_id;return '<section class="neon-panel market-panel"><div class="fan-section-head"><div><p class="arc-kicker">'+esc(divisionLabel(m.division))+'</p><h2>'+esc(pickCategory(m.category))+'</h2></div><span class="market-badge">'+(hasBet?'MY PICK 접수됨':open?'PICK OPEN':m.market_status==='settled'?'결과 정산':'접수 마감')+'</span></div><p class="fan-note">마감 '+esc(new Date(m.lock_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))+' KST · 누적 사용 '+points(m.total_stake)+'</p><div class="pick-teams">'+rows.filter(r=>r.team_id).map(r=>{const share=r.total_stake?Math.round(r.team_stake/r.total_stake*100):0;return '<button class="pick-team '+(r.user_team_id===r.team_id?'is-picked':'')+'" data-team="'+esc(r.team_id)+'" data-market="'+esc(r.market_id)+'" '+(!open||hasBet?'disabled':'')+'><span>'+esc(r.team_name)+'</span><strong>×'+Number(r.live_odds).toFixed(2)+'</strong><small>포인트 비중 '+share+'% · '+points(r.team_stake)+'</small><progress max="100" value="'+share+'" aria-label="'+esc(r.team_name)+' 포인트 비중">'+share+'%</progress><b>'+(r.user_team_id===r.team_id?'✓ MY PICK':open&&!hasBet?'이 팀 선택 →':'접수 종료')+'</b></button>';}).join('')+'</div>'+(!rows.some(r=>r.team_id)?'<p>확정된 참가팀을 기다리고 있습니다.</p>':'')+'</section>';}).join('');
}
async function renderHistory(){
 if(!fanUser)return;
 const q=await db.from('tg_prediction_bets').select('id,team_id,stake,odds_locked,potential_payout,payout,status,created_at').eq('user_id',fanUser.id).order('created_at',{ascending:false}).limit(50);
 if(q.error){fp('historyRows').textContent='예측 내역을 불러오지 못했습니다. 새로고침해 주세요.';return;}
 if(!q.data.length){fp('historyRows').innerHTML='<p>아직 접수한 예측이 없습니다. 보드가 열리면 첫 번째 팀을 골라보세요.</p>';return;}
 const ids=[...new Set(q.data.map(b=>b.team_id))];const tq=await db.from('tg_teams').select('id,team_name').in('id',ids);const names=Object.fromEntries((tq.data||[]).map(t=>[t.id,t.team_name]));
 fp('historyRows').innerHTML='<p class="fan-note">최근 50건 · 전체 경기</p>'+q.data.map(b=>'<article class="pick-history '+(b.status==='won'?'history-win':'')+'"><div><span class="market-badge">'+pickStatus(b.status)+'</span><h3>'+esc(names[b.team_id]||'팀 정보 비공개')+'</h3><small>'+esc(new Date(b.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))+' KST</small></div><div><b>'+points(b.stake)+' · ×'+Number(b.odds_locked).toFixed(2)+'</b><p>'+(['won','lost','refunded'].includes(b.status)?'지급 '+points(b.status==='refunded'?b.stake:b.payout):'적중 시 지급 '+points(b.potential_payout))+'</p></div></article>').join('');
}
async function refreshPicks(){
 if(refreshBusy||pickBusy)return;refreshBusy=true;fp('refreshPicks').disabled=true;
 try{
 const results=await Promise.allSettled([pickRpc('tg_prediction_board',{p_event_slug:C.eventSlug}),fanUser?pickRpc('arc_my_account'):Promise.resolve(null)]);
 if(results[0].status==='fulfilled'){pickRows=results[0].value||[];renderBoard();}else{pickRows=[];fp('pickBoard').innerHTML='<p class="neon-panel">예측 보드를 불러오지 못했습니다. 새로고침해 주세요.</p>';}
 fanAccount=results[1].status==='fulfilled'?results[1].value?.[0]:null;renderWallet();await renderHistory();
 }finally{refreshBusy=false;fp('refreshPicks').disabled=false;}
}
function estimatePick(){const stake=Number(fp('pickStake').value),balance=Number(fanAccount?.balance||0);fp('pickEstimate').innerHTML='<span>예상 지급 · 적중 시</span><strong>'+points(Math.round((Number.isFinite(stake)?stake:0)*Number(selectedPick?.live_odds||0)))+'</strong><p>사용 후 잔액 '+points(balance-(Number.isFinite(stake)?stake:0))+'</p>';fp('confirmPick').disabled=pickBusy||!Number.isInteger(stake)||stake<100||stake%100!==0||stake>balance;}
fp('pickBoard').addEventListener('click',e=>{const b=e.target.closest('[data-team]');if(!b||b.disabled)return;if(!fanUser){location.href='account.html?next=fanpick.html';return;}if(!fanAccount){fp('pickMessage').textContent='포인트를 새로고침한 뒤 선택해 주세요.';return;}selectedPick=pickRows.find(r=>r.team_id===b.dataset.team&&r.market_id===b.dataset.market);if(!selectedPick)return;fp('pickDialogTitle').textContent=selectedPick.team_name;fp('pickMarketLabel').textContent=divisionLabel(selectedPick.division)+' · '+pickCategory(selectedPick.category);fp('pickStake').value=100;fp('pickStake').max=fanAccount.balance;fp('dialogError').textContent='';estimatePick();fp('pickDialog').showModal();});
fp('pickStake').addEventListener('input',estimatePick);document.querySelectorAll('[data-stake]').forEach(b=>b.onclick=()=>{fp('pickStake').value=b.dataset.stake;estimatePick();});
fp('closePick').onclick=()=>{if(!pickBusy)fp('pickDialog').close();};fp('pickDialog').addEventListener('cancel',e=>{if(pickBusy)e.preventDefault();});fp('refreshPicks').onclick=refreshPicks;
fp('pickForm').onsubmit=async e=>{
 e.preventDefault();if(pickBusy||!selectedPick||!e.target.reportValidity())return;const stake=Number(fp('pickStake').value);if(!Number.isInteger(stake)||stake<100||stake%100||stake>Number(fanAccount?.balance))return;
 pickBusy=true;fp('confirmPick').disabled=true;fp('closePick').disabled=true;fp('pickStake').disabled=true;fp('confirmPick').textContent='접수 중…';fp('dialogError').textContent='';const selected={...selectedPick};const before=fanAccount.balance;
 try{const rows=await pickRpc('tg_place_prediction_bet',{p_market_id:selected.market_id,p_team_id:selected.team_id,p_stake:stake});const result=rows?.[0];if(!result)throw new Error('NO_RECEIPT');fanAccount.balance=result.balance;renderWallet();fp('pickDialog').close();fp('pickMessage').innerHTML='<section class="pick-receipt"><p class="arc-kicker">✓ PICK LOCKED IN</p><h2>'+esc(selected.team_name)+'</h2><p>'+points(before)+' → <strong>'+points(result.balance)+'</strong></p><p>'+points(stake)+' 사용 · 확정 배율 ×'+Number(result.odds_locked).toFixed(2)+'<br>적중 시 지급 '+points(result.potential_payout)+'</p><a href="#pickHistory">내 예측 확인 ↓</a></section>';fp('pickMessage').scrollIntoView({behavior:'smooth',block:'center'});
 }catch(err){fp('dialogError').textContent=pickError(err);}
 finally{pickBusy=false;fp('closePick').disabled=false;fp('pickStake').disabled=false;fp('confirmPick').textContent='이 예측으로 확정';await refreshPicks();estimatePick();}
};
(async()=>{try{fanUser=await currentUser();if(fanUser)await pickRpc('arc_account_bootstrap',{p_display_name:null});await refreshPicks();}catch(e){fp('fanWallet').textContent='계정 정보를 불러오지 못했습니다. 페이지를 새로고침해 주세요.';fp('pickBoard').textContent='잠시 후 다시 확인해 주세요.';}})();
