const fp=id=>document.getElementById(id),points=v=>Number(v||0).toLocaleString('ko-KR')+' P';
const pickCategory=v=>({MM:'MEN’S DOUBLES',WW:'WOMEN’S DOUBLES',MIXED:'MIXED DOUBLES'}[v]||v);
const pickStatus=v=>({pending:'PENDING',won:'WIN',lost:'LOSS',refunded:'REFUNDED'}[v]||'PENDING');
let fanUser=null,fanAccount=null,pickRows=[],selectedPick=null,pickBusy=false,refreshBusy=false;
async function pickRpc(name,args){const q=await db.rpc(name,args);if(q.error)throw q.error;return q.data;}
function pickError(e){const m=String(e?.message||e);return Object.entries({AUTH_REQUIRED:'Log in and try again.',INVALID_STAKE:'Enter at least 100 P in 100 P increments.',MARKET_LOCKED:'This market is closed.',BET_ALREADY_PLACED:'You already picked in this market. Check your history.',INSUFFICIENT_POINTS:'Not enough PLAY POINT.',TEAM_NOT_IN_MARKET:'This team is not available. Refresh the board.',FAN_PROFILE_REQUIRED:'Refresh your account and try again.'}).find(([k])=>m.includes(k))?.[1]||'Could not confirm this pick. Refresh your history before trying again.';}
function renderWallet(){
 if(!fanUser){fp('fanWallet').innerHTML='<p class="arc-kicker">PLAYER NOT CONNECTED</p><h2>BE PART OF THE GAME.</h2><p>Log in to see your points and pick stats.</p><a class="arc-button neon-pink" href="account.html?next=fanpick.html">LOG IN / SIGN UP →</a>';return;}
 const a=fanAccount;if(!a){fp('fanWallet').innerHTML='<p>Could not load your points. Refresh the page.</p>';return;}
 fp('fanWallet').innerHTML='<div class="wallet-top"><div><p class="arc-kicker">'+esc(a.display_name)+' / PLAY POINT</p><strong class="wallet-balance">'+points(a.balance)+'</strong><span class="fan-note">AVAILABLE POINTS</span></div><a class="arc-button" href="my.html">MY ACCOUNT ↗</a></div><div class="fan-stats"><div><span>HIT RATE</span><b>'+(a.settled_bets?Number(a.hit_rate).toFixed(1)+'%':'—')+'</b></div><div><span>WINS / SETTLED</span><b>'+Number(a.wins||0)+' / '+Number(a.settled_bets||0)+'</b></div><div><span>NET POINTS</span><b>'+(a.net_win>0?'+':'')+points(a.net_win)+'</b></div><div><span>TOTAL STAKED</span><b>'+points(a.total_staked)+'</b></div></div><p class="fan-note">Stats cover all picks; hit rate and net points count settled picks only.</p>';
}
function renderBoard(){
 if(!pickRows.length){fp('pickBoard').innerHTML='<section class="neon-panel empty-cabinet"><span class="pixel-icon" aria-hidden="true">◈</span><p class="arc-kicker">NEXT GAME LOADING</p><h2>PICK BOARD COMING SOON</h2><p>Picks open here when markets go live.<br>Explore the teams and game in the meantime.</p><div class="arc-actions"><a class="arc-button" href="teams.html">VIEW TEAMS →</a><a class="arc-button" href="event.html">THE GAME →</a></div></section>';return;}
 const groups=Map.groupBy?Map.groupBy(pickRows,r=>r.market_id):pickRows.reduce((m,r)=>(m.has(r.market_id)?m.get(r.market_id).push(r):m.set(r.market_id,[r]),m),new Map());
 fp('pickBoard').innerHTML=[...groups.values()].map(rows=>{const m=rows[0],open=m.market_status==='open'&&new Date(m.lock_at)>new Date(),hasBet=!!m.user_bet_id;return '<section class="neon-panel market-panel"><div class="fan-section-head"><div><p class="arc-kicker">'+esc(divisionLabel(m.division))+'</p><h2>'+esc(pickCategory(m.category))+'</h2></div><span class="market-badge">'+(hasBet?'PICK LOCKED':open?'PICK OPEN':m.market_status==='settled'?'SETTLED':'CLOSED')+'</span></div><p class="fan-note">CLOSES '+esc(new Date(m.lock_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))+' KST · STAKED '+points(m.total_stake)+'</p><div class="pick-teams">'+rows.filter(r=>r.team_id).map(r=>{const share=r.total_stake?Math.round(r.team_stake/r.total_stake*100):0;return '<button class="pick-team '+(r.user_team_id===r.team_id?'is-picked':'')+'" data-team="'+esc(r.team_id)+'" data-market="'+esc(r.market_id)+'" '+(!open||hasBet?'disabled':'')+'><span>'+esc(r.team_name)+'</span><strong>×'+Number(r.live_odds).toFixed(2)+'</strong><small>POINT SHARE '+share+'% · '+points(r.team_stake)+'</small><progress max="100" value="'+share+'" aria-label="'+esc(r.team_name)+' POINT SHARE">'+share+'%</progress><b>'+(r.user_team_id===r.team_id?'✓ MY PICK':open&&!hasBet?'PICK THIS TEAM →':'CLOSED')+'</b></button>';}).join('')+'</div>'+(!rows.some(r=>r.team_id)?'<p>WAITING FOR CONFIRMED TEAMS.</p>':'')+'</section>';}).join('');
}
async function renderHistory(){
 if(!fanUser)return;
 const q=await db.from('tg_prediction_bets').select('id,team_id,stake,odds_locked,potential_payout,payout,status,created_at').eq('user_id',fanUser.id).order('created_at',{ascending:false}).limit(50);
 if(q.error){fp('historyRows').textContent='Could not load your picks. Refresh.';return;}
 if(!q.data.length){fp('historyRows').innerHTML='<p>No picks yet. Choose a team when the board opens.</p>';return;}
 const ids=[...new Set(q.data.map(b=>b.team_id))];const tq=await db.from('tg_teams').select('id,team_name').in('id',ids);const names=Object.fromEntries((tq.data||[]).map(t=>[t.id,t.team_name]));
 fp('historyRows').innerHTML='<p class="fan-note">LATEST 50 PICKS · ALL GAMES</p>'+q.data.map(b=>'<article class="pick-history '+(b.status==='won'?'history-win':'')+'"><div><span class="market-badge">'+pickStatus(b.status)+'</span><h3>'+esc(names[b.team_id]||'TEAM UNAVAILABLE')+'</h3><small>'+esc(new Date(b.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))+' KST</small></div><div><b>'+points(b.stake)+' · ×'+Number(b.odds_locked).toFixed(2)+'</b><p>'+(['won','lost','refunded'].includes(b.status)?'PAID '+points(b.status==='refunded'?b.stake:b.payout):'POTENTIAL PAYOUT '+points(b.potential_payout))+'</p></div></article>').join('');
}
async function refreshPicks(){
 if(refreshBusy||pickBusy)return;refreshBusy=true;fp('refreshPicks').disabled=true;
 try{
 const results=await Promise.allSettled([pickRpc('tg_prediction_board',{p_event_slug:C.eventSlug}),fanUser?pickRpc('arc_my_account'):Promise.resolve(null)]);
 if(results[0].status==='fulfilled'){pickRows=results[0].value||[];renderBoard();}else{pickRows=[];fp('pickBoard').innerHTML='<p class="neon-panel">Could not load the board. Refresh.</p>';}
 fanAccount=results[1].status==='fulfilled'?results[1].value?.[0]:null;renderWallet();await renderHistory();
 }finally{refreshBusy=false;fp('refreshPicks').disabled=false;}
}
function estimatePick(){const stake=Number(fp('pickStake').value),balance=Number(fanAccount?.balance||0);fp('pickEstimate').innerHTML='<span>POTENTIAL PAYOUT</span><strong>'+points(Math.round((Number.isFinite(stake)?stake:0)*Number(selectedPick?.live_odds||0)))+'</strong><p>BALANCE AFTER PICK '+points(balance-(Number.isFinite(stake)?stake:0))+'</p>';fp('confirmPick').disabled=pickBusy||!Number.isInteger(stake)||stake<100||stake%100!==0||stake>balance;}
fp('pickBoard').addEventListener('click',e=>{const b=e.target.closest('[data-team]');if(!b||b.disabled)return;if(!fanUser){location.href='account.html?next=fanpick.html';return;}if(!fanAccount){fp('pickMessage').textContent='Refresh your balance before picking.';return;}selectedPick=pickRows.find(r=>r.team_id===b.dataset.team&&r.market_id===b.dataset.market);if(!selectedPick)return;fp('pickDialogTitle').textContent=selectedPick.team_name;fp('pickMarketLabel').textContent=divisionLabel(selectedPick.division)+' · '+pickCategory(selectedPick.category);fp('pickStake').value=100;fp('pickStake').max=fanAccount.balance;fp('dialogError').textContent='';estimatePick();fp('pickDialog').showModal();});
fp('pickStake').addEventListener('input',estimatePick);document.querySelectorAll('[data-stake]').forEach(b=>b.onclick=()=>{fp('pickStake').value=b.dataset.stake;estimatePick();});
fp('closePick').onclick=()=>{if(!pickBusy)fp('pickDialog').close();};fp('pickDialog').addEventListener('cancel',e=>{if(pickBusy)e.preventDefault();});fp('refreshPicks').onclick=refreshPicks;
fp('pickForm').onsubmit=async e=>{
 e.preventDefault();if(pickBusy||!selectedPick||!e.target.reportValidity())return;const stake=Number(fp('pickStake').value);if(!Number.isInteger(stake)||stake<100||stake%100||stake>Number(fanAccount?.balance))return;
 pickBusy=true;fp('confirmPick').disabled=true;fp('closePick').disabled=true;fp('pickStake').disabled=true;fp('confirmPick').textContent='SUBMITTING…';fp('dialogError').textContent='';const selected={...selectedPick};const before=fanAccount.balance;
 try{const rows=await pickRpc('tg_place_prediction_bet',{p_market_id:selected.market_id,p_team_id:selected.team_id,p_stake:stake});const result=rows?.[0];if(!result)throw new Error('NO_RECEIPT');fanAccount.balance=result.balance;renderWallet();fp('pickDialog').close();fp('pickMessage').innerHTML='<section class="pick-receipt"><p class="arc-kicker">✓ PICK LOCKED IN</p><h2>'+esc(selected.team_name)+'</h2><p>'+points(before)+' → <strong>'+points(result.balance)+'</strong></p><p>'+points(stake)+' STAKED · LOCKED ODDS ×'+Number(result.odds_locked).toFixed(2)+'<br>POTENTIAL PAYOUT '+points(result.potential_payout)+'</p><a href="#pickHistory">VIEW MY PICKS ↓</a></section>';fp('pickMessage').scrollIntoView({behavior:'smooth',block:'center'});
 }catch(err){fp('dialogError').textContent=pickError(err);}
 finally{pickBusy=false;fp('closePick').disabled=false;fp('pickStake').disabled=false;fp('confirmPick').textContent='LOCK IN PICK';await refreshPicks();estimatePick();}
};
(async()=>{try{fanUser=await currentUser();if(fanUser)await pickRpc('arc_account_bootstrap',{p_display_name:null});await refreshPicks();}catch(e){fp('fanWallet').textContent='Could not load your account. Refresh the page.';fp('pickBoard').textContent='Please try again shortly.';}})();
